### PR TITLE
Fix/b2b polish

### PR DESCRIPTION
**Pull request by bengarvey**
This fixed some of the issues listed here
https://github.com/RJMetrics/magenerator/issues/54

1. Adds reserved_order_id
2. Raises the number of quotes to 1000
3. Fixed blank tables (company_credit and company_advanced_customer_entity)
4. Only 5 shared catalogs now
5. Added the admin_users table
6. Fixed company.status and company.customer_group_id (sort of)
7. Added dates for customer expiration period

This doesn't address the data quality issues and foreign keys, which IMO should be in a separate PR.

### CODE REVIEW

**Comment by stefmontgomery** [comment]
1. Missing LOAD DATA statements in README.md for admin_users, sales_order, sales_order_item, sales_order_address, quote, quote_item, store, shared_catalog tables, negotiable_quote, negotiable_quote_comment, negotiable_quote_history, company_advanced_customer_entity tables, company_credit, company_payment tables.

2. Line 110 should be calling `generateCompanyAdvancedCustomerEntities()` instead of `generateCompanyAdvancedCustomerEntity()`. company_advanced_customer_entity.csv is blank because of this.

3. Is `expiration_period` supposed to be on `quote` or `negotiable_quote`? Issue #54 makes it sound like it should be on `quote`. It's on `negotiable_quote` now.

**Comment by ckelley-magento** [comment]
3. `expiration_period` is on `negotiable_quote`; that was my mistake. I updated that comment to move it.

**Comment by bengarvey** [comment]
1. I'm going to leave out the LOAD statements for now, as I'm going to redo the whole data loading thing into a script. It's pretty cumbersome right now with 22 tables.

2. Fixed.

3. So we're good here then?

@stefmontgomery back to you

**Review by stefmontgomery — APPROVED** [review]

**Review by stefmontgomery — APPROVED** [review]
Approved.

**Pull request merged**
